### ISSUE TITLE
Still getting errors after upgrade.

### ISSUE THREAD

**Issue by bryceismad1** [originaluko/haveibeenpwned#3] opened 2019-02-05 03:27 UTC
I installed the 1.3 version and it still says 

Get-PwnedAccount : Forbidden - no user agent has been specified in the request.

when using the function

**Comment by originaluko** [comment] 2019-02-05 11:53
Still working for me.  Can you check if an old version of the module is still loaded in PowerShell? You may have both loaded side by side.  

Get-Module -ListAvailable or just Get-Module HaveIBeenPwned

You can also specify your own User Agent string using -UserAgent

**Comment by jonatj** [comment] 2019-02-19 07:41
I was getting the "Forbidden" error when using a custom string.  When I used "Chrome 60" it worked.

Ex. Get-PwnedAccount -emailaddress youremail@gmail.com -UserAgent "Chrome 60"

Edit: It worked once, then the next session it didn't. :-(

**Comment by originaluko** [comment] 2019-10-24 06:27
Closing this issue as it's based on an old version. The module has since been updated to version 3 with support for authorisation and confirmed working with a user agent. Thanks

**Closed as completed by originaluko** 2019-10-24 06:27 UTC
